version: '3.9'
services:
  fake-facebook:
    build:
      context: ./fake-facebook
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./fake-facebook/src:/home/node/app/src
      - ./fake-facebook/nodemon.json:/home/node/app/nodemon.json
      - /Users/billy/ramzor/ramzor/runlogs:/usr/log
    container_name: fake-facebook
    environment:
      SERVER_PORT: 3031
      DEBUG_PORT: 9229
    ports:
      - '3031:3031'
      - '9229:9229'
    expose:
      - '3031'
      - '9229'
    command: npm run dev
  fake-google:
    build:
      context: ./fake-google
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./fake-google/src:/home/node/app/src
      - ./fake-google/nodemon.json:/home/node/app/nodemon.json
      - /Users/billy/ramzor/ramzor/runlogs:/usr/log
    container_name: fake-google
    environment:
      SERVER_PORT: 3032
      DEBUG_PORT: 9230
    ports:
      - '3032:3032'
      - '9230:9230'
    expose:
      - '3032'
      - '9230'
    command: npm run dev
  fake-klaviyo:
    build:
      context: ./fake-klaviyo
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./fake-klaviyo/src:/home/node/app/src
      - ./fake-klaviyo/nodemon.json:/home/node/app/nodemon.json
      - /Users/billy/ramzor/ramzor/runlogs:/usr/log
    container_name: fake-klaviyo
    environment:
      SERVER_PORT: 3034
      DEBUG_PORT: 9231
    ports:
      - '3034:3034'
      - '9231:9231'
    expose:
      - '3034'
      - '9231'
    command: npm run dev
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - .redis:/data
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ImAWhale
